### ISSUE TITLE
planning pva

### ISSUE THREAD

**Issue by maxvisser** [TeamSnowflake/StemApp-documentatie#2]
klopt de planning nog steeds? evt. plan van aanpak opstellen met ons samen waarin we duidelijke afspraken maken omtrent:
- wanneer jullie wat nodig hebben van ons
- wat jullie exact willen gaan testen

Misschien een stemapp-fieldtest repository aanmaken waarin we issues kunnen aanmaken wat er moet gebeuren

**Comment by maxvisser** [comment]
![planning](https://user-images.githubusercontent.com/10818702/38362592-b3b980dc-38d1-11e8-87bd-5d618f3db0cc.png)

**Comment by Fekkes** [comment]
Er wordt in de 2e periode van ons project (begint op 16-04) een nieuwe versie van het PvA opgeleverd. Wij zullen dan onze planning updaten. 
Ik heb inmiddels ook een repository aangemaakt voor de fieldtest.
